global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:5000']
  
  - job_name: 'ai-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['ai-service:8000']
